import { useEffect,useRef,useState,type ReactNode } from "react";
import { Activity,Flame,RefreshCw,Send,ShieldAlert,ShieldCheck,Sliders,Terminal as TerminalIcon,Trash2,Wifi } from "lucide-react";
import type { RuntimeRiskProfile,RuntimeStatus,Settings } from "../types";
import { apiRequest } from "../utils/frontendContract";
interface Props { settings:Settings; updateSetting:(key:string,value:number)=>void; systemLogs?:string[]; riskProfile?:RuntimeRiskProfile|null; runtimeStatus?:RuntimeStatus|null; }
const duration=(ms:number|null|undefined)=>ms==null?"—":`${Math.round(ms/60000)} minutes`;
export function SettingsPage({settings,updateSetting,systemLogs=[],riskProfile,runtimeStatus}:Props){
 const[bybitTesting,setBybitTesting]=useState(false);const[bybitStatus,setBybitStatus]=useState<any>(null);const[telegramTesting,setTelegramTesting]=useState(false);const[telegramStatus,setTelegramStatus]=useState<any>(null);const[localLogs,setLocalLogs]=useState<string[]>([]);const terminalBottomRef=useRef<HTMLDivElement>(null);
 const add=(m:string)=>setLocalLogs(p=>[...p.slice(-100),`[${new Date().toLocaleTimeString()}] ${m}`]);
 const testBybit=async()=>{setBybitTesting(true);try{const d=await apiRequest<any>("/api/test-bybit");setBybitStatus(d);add(`Bybit network reachable (${d.latencyMs}ms). This public ping does not prove account authentication.`);}catch(e:any){setBybitStatus({success:false,error:e.message});add(`Bybit network test failed: ${e.message}`);}finally{setBybitTesting(false)}};
 const testTelegram=async()=>{setTelegramTesting(true);try{const d=await apiRequest<any>("/api/test-telegram",{method:"POST"});setTelegramStatus({success:true,message:d.message||"Delivered"});add("Telegram test alert delivered");}catch(e:any){setTelegramStatus({success:false,error:e.message});add(`Telegram alert failed: ${e.message}`);}finally{setTelegramTesting(false)}};
 useEffect(()=>{void testBybit();add("Diagnostics initialized. Risk values below come from the backend runtime profile.");},[]);useEffect(()=>{terminalBottomRef.current?.scrollIntoView({behavior:"smooth"})},[localLogs,systemLogs]);
 const controls=riskProfile?[["Leverage",`${riskProfile.leverage}x`],["Position margin max",`$${riskProfile.positionMarginUsdt}`],["Base notional",`$${riskProfile.baseNotionalUsdt}`],["Max concurrent positions",String(riskProfile.maxPositions)],["Same-symbol duplicate",riskProfile.duplicateSymbolBlocked?"Blocked":"Allowed"],["Post-close cooldown",duration(riskProfile.sameSymbolCooldownMs)],["Daily net entry breaker",`$${riskProfile.dailyEntryBreakerNetUsdt}`],["3-loss pause",duration(riskProfile.consecutiveLossPauseMs)],["Breaker scope",riskProfile.breakerScope==="new_entries_only"?"New entries only":riskProfile.breakerScope],["Adaptive SL range",`${riskProfile.adaptiveSlMinPercent.toFixed(2)}%–${riskProfile.adaptiveSlMaxPercent.toFixed(2)}%`],["Stop-loss discipline",riskProfile.stopLossNeverWidens?"Never widened":"Backend-defined"]]:[];
 return <div className="space-y-6 max-w-5xl"><header className="pb-4 border-b border-neutral-800"><h1 className="text-3xl font-bold tracking-tight text-white mb-1">Risk & Settings</h1><p className="text-neutral-400 text-sm">Runtime truth comes from backend settings/risk profile; public network reachability is not treated as account authentication.</p></header>
 <div className="grid grid-cols-1 md:grid-cols-2 gap-6"><div className="bg-neutral-900 border border-neutral-800 rounded-xl p-5"><div className="flex items-center justify-between mb-4"><div className="flex items-center gap-2.5"><Wifi className="w-5 h-5 text-blue-400"/><div><h2 className="font-bold text-white">Bybit Connectivity</h2><p className="text-xs text-neutral-400">Public network, private REST auth, and private WS are separate states</p></div></div></div><div className="bg-neutral-950 rounded-lg border border-neutral-800 p-3 text-xs space-y-2 mb-4"><Row l="Network reachable" v={runtimeStatus?runtimeStatus.bybitNetworkReachable?"Yes":"No":"Unknown"}/><Row l="Account authenticated" v={runtimeStatus?runtimeStatus.accountAuthenticated?"Yes":"No":"Unknown"}/><Row l="Trading / Private API" v={runtimeStatus?runtimeStatus.privateApiHealthy?"Healthy":"Unhealthy":"Unknown"}/><Row l="Bybit Private WS" v={runtimeStatus?runtimeStatus.privateWsConnected?(runtimeStatus.privateWsAuthenticated?"Connected + authenticated":"Connected / auth pending"):"Disconnected":"Unknown"}/><Row l="Public ping latency" v={bybitStatus?.latencyMs!==undefined?`${bybitStatus.latencyMs} ms`:"—"}/>{runtimeStatus?.error&&<p className="text-rose-400">{runtimeStatus.error}</p>}</div><button onClick={testBybit} disabled={bybitTesting} className="w-full flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-semibold text-xs disabled:opacity-50"><RefreshCw className={`w-3.5 h-3.5 ${bybitTesting?"animate-spin":""}`}/>Test Network Reachability</button></div>
 <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-5"><div className="flex items-center gap-2.5 mb-4"><Send className="w-5 h-5 text-indigo-400"/><div><h2 className="font-bold text-white">Telegram Alerts</h2><p className="text-xs text-neutral-400">Signal and execution notifications</p></div></div>{telegramStatus&&<div className={`rounded-lg border p-3 text-xs mb-4 ${telegramStatus.success?"border-emerald-500/30 text-emerald-300":"border-rose-500/30 text-rose-300"}`}>{telegramStatus.success?telegramStatus.message:telegramStatus.error}</div>}<button onClick={testTelegram} disabled={telegramTesting} className="w-full flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-neutral-800 hover:bg-neutral-700 text-white font-semibold text-xs disabled:opacity-50"><Send className="w-3.5 h-3.5"/>Send Test Ping to Telegram</button></div></div>
 <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-5 sm:p-6"><div className="flex items-center gap-3 mb-4"><ShieldCheck className="w-5 h-5 text-emerald-400"/><div><h2 className="font-bold text-white">Canonical Execution & Risk Profile</h2><p className="text-xs text-neutral-400">Values are returned by the trading engine, not duplicated in frontend constants.</p></div></div>{controls.length?<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">{controls.map(([l,v])=><div key={l} className="bg-neutral-950 border border-neutral-800 rounded-lg p-3"><p className="text-[11px] text-neutral-500">{l}</p><p className="text-sm font-bold text-white mt-1">{v}</p></div>)}</div>:<div className="text-sm text-amber-300">Runtime risk profile unavailable.</div>}</div>
 <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-5 sm:p-6"><div className="flex items-center gap-3 mb-5"><Sliders className="w-5 h-5 text-blue-400"/><div><h2 className="font-bold text-white">Editable Bracket References</h2><p className="text-xs text-neutral-400">Editable settings are sent to the backend; locked risk controls above remain authoritative.</p></div></div><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><SettingInput label="Take Profit %" value={settings.tpPercent} min={0.1} max={10} step={0.1} onChange={v=>updateSetting("tpPercent",v)} icon={<Activity className="w-4 h-4 text-emerald-400"/>}/><SettingInput label="SL risk reference %" value={settings.slPercent} min={0.1} max={5} step={0.1} onChange={v=>updateSetting("slPercent",v)} icon={<ShieldAlert className="w-4 h-4 text-rose-400"/>}/><SettingInput label="Trailing Stop %" value={settings.trailingStopPercent} min={0.1} max={5} step={0.1} onChange={v=>updateSetting("trailingStopPercent",v)} icon={<Flame className="w-4 h-4 text-amber-400"/>}/></div></div>
 <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-5"><div className="flex items-center justify-between mb-3 pb-3 border-b border-neutral-800"><div className="flex items-center gap-2"><TerminalIcon className="w-5 h-5 text-emerald-400"/><h2 className="font-bold text-white">System Diagnostics</h2></div><button onClick={()=>setLocalLogs([])} className="p-1.5 rounded-lg bg-neutral-950 text-neutral-400 border border-neutral-800 text-xs flex items-center gap-1"><Trash2 className="w-3.5 h-3.5"/>Clear</button></div><div className="bg-neutral-950 rounded-xl p-4 font-mono text-xs h-56 overflow-y-auto border border-neutral-800 space-y-1">{[...localLogs,...systemLogs].map((log,i)=><div key={`${i}-${log}`} className={log.includes("Error")?"text-rose-400":"text-neutral-300"}>{log}</div>)}<div ref={terminalBottomRef}/></div></div></div>;
}
function Row({l,v}:{l:string;v:string}){return <div className="flex justify-between gap-3"><span className="text-neutral-500">{l}</span><span className="text-white text-right">{v}</span></div>}
function SettingInput({label,value,min,max,step,onChange,icon}:{label:string;value:number;min:number;max:number;step:number;onChange:(value:number)=>void;icon:ReactNode}){return <div className="bg-neutral-950 border border-neutral-800 rounded-xl p-4"><label className="text-xs text-neutral-300 flex items-center gap-2 mb-2">{icon}{label}</label><input type="number" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))} className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-3 py-2 text-sm text-white"/></div>}
